var gulp = require('gulp');
var browserify = require('browserify');
var source = require('vinyl-source-stream');
var concat = require('gulp-concat');
var uglify = require('gulp-uglify')
var utilities = require('gulp-util'); //environmental variables //
var del = require('del'); // clean tasks //
var jshint = require('gulp-jshint');
var buildProduction = utilities.env.production;
